services:
  postgres:
    image: postgres:15
    container_name: gantt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gantt_db
      POSTGRES_USER: root_iman
      POSTGRES_PASSWORD: admin@
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
